Sanjam?Upgrded description and Title tags in Deriv API
binary-com/deriv-developers-portal pull request #195
Opened 2022-07-29 04:56 UTC by sanjam-deriv

2022-07-29 05:16 UTC, matin-binary approved these changes

2022-07-29 08:12 UTC, adam-deriv requested changes
adjust the styling so it still matches production while keeping what SEO needs adjusted

2022-07-29 08:40 UTC, adam-deriv approved these changes

2022-08-04 14:15 UTC, adamrrudolf approved these changes

2022-08-04 14:16 UTC, merged