fix:Added rebranding
binary-com/deriv-developers-portal pull request #291
Opened 2023-02-23 06:33 UTC by sanjam-deriv

2023-02-23 06:57 UTC, hubert-deriv requested changes

2023-02-23 06:57 UTC, hubert-deriv commented on src/components/global/Header/Header.module.scss
> +    border-bottom: 1px var(--gray-01) solid;
A small nitpick, isn't it `1px solid var(--gray-01);`? Looks like you flipped the color and the line type (solid). Does it still work like this?

2023-02-23 06:59 UTC, hubert-deriv commented on src/components/global/Header/Header.module.scss
> +    border-bottom: 1px var(--gray-01) solid;
NVM, I just checked on the deployment link, looks like it does

2023-02-23 07:02 UTC, hubert-deriv approved these changes

2023-02-23 07:12 UTC, amina-deriv approved these changes

2023-03-02 07:26 UTC, matin-deriv approved these changes

2023-03-03 12:33 UTC, merged